name: 'payments'
version: '1.0.0'
config-version: 2

profile: 'payments'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  payments:
    staging:
      +materialized: view
    marts:
      +materialized: table